In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import wandb
from datasets import Dataset
from transformers import AutoTokenizer
from finetune import train_eval_model
from experiment import preprocess_text

2026-05-23 23:46:06.122570: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1779569166.148869  270798 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1779569166.156684  270798 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1779569166.181666  270798 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1779569166.181688  270798 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1779569166.181691  270798 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1779569166.181694  270798 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-05-23 23:46:06.188194: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/lib/python3.9/dist-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

In [2]:
models_config = [
    ("sentence-transformers/all-MiniLM-L6-v2", "outputs/emotion-classifier-minilm")
]
label_config = [
    {0: 'neutral', 0.5: 'present'}, 
    {0: 'neutral', 0.5: 'medium', 1.5: 'high'},
    {0: 'neutral', 0.5: 'moderate', 1.0: 'high', 1.5: 'strong', 2.0: 'extreme'}
]

In [3]:
def preprocess(example):
    return {'text': preprocess_text(example['text']), 'labels': example['labels']}

def load_emotionality_dataset(tokenizer, label_bounds = {0: 'present'}):
    DATA_PATH = Path("../data/2026-05-21/corpus_emotions.json")
    data = pd.read_json(DATA_PATH)
    labels = pd.cut(
        data['emotionality'], 
        bins=list(label_bounds.keys()) + [np.max(data['emotionality'])+1],
        labels=list(label_bounds.values()),
        right=False
    ).astype('object')
    data = Dataset.from_dict({'text': data['content'], 'labels': labels})
    data = data.map(preprocess)
    labels_map = {label: ind for ind, label in enumerate(set(data['labels']))}

    def tokenize(example):
        labels = list(map(lambda m: labels_map.get(m), example['labels']))
        example = tokenizer(example["text"], padding="max_length", truncation=True)
        example['labels'] = labels
        return example

    final_dst = data.map(tokenize, batched=True, remove_columns=['text'])
    final_dst.set_format(type="torch")
    return final_dst, labels_map

In [ ]:
for model_name, output_dir in models_config:
    for ind, label_bounds in enumerate(label_config):
        print(f"Training model for emotion detection with model {model_name} using discretization to {len(label_bounds)} classes")
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        ds, labels_map = load_emotionality_dataset(tokenizer, label_bounds=label_bounds)
        run = wandb.init(project="emotion-detection-lt", name=f"{model_name}-{len(label_bounds)}class-{ind}")
        train_eval_model(
            model_name=model_name,
            dataset=ds,
            labels_map=labels_map,
            output_dir=f"{output_dir}-{ind}", 
            batch_size=16, 
            num_epochs=20, 
            eval_batch_size=16,
            report_to=['tensorboard', 'wandb']
        )

Training model for emotion detection with model sentence-transformers/all-MiniLM-L6-v2 using discretization to 2 classes

Map:   0%|          | 0/2660 [00:00<?, ? examples/s]

Map:   0%|          | 0/2660 [00:00<?, ? examples/s]

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/paulius/.netrc.
wandb: Currently logged in as: danpaulius (danpaulius-ktu) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

Stringifying the column:   0%|          | 0/2660 [00:00<?, ? examples/s]

Casting to class labels:   0%|          | 0/2660 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at sentence-transformers/all-MiniLM-L6-v2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
The model is already on multiple devices. Skipping the move to device specified in `args`.

[2026-05-23 23:46:28,343] [INFO] [real_accelerator.py:260:get_accelerator] Setting ds_accelerator to cuda (auto detect)

/usr/bin/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status

[2026-05-23 23:46:36,825] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False

***** Running training *****
  Num examples = 1,861
  Num Epochs = 20
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 2,340
  Number of trainable parameters = 338,690
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"

***** Running Evaluation *****
  Num examples = 399
  Batch size = 16
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
Saving model checkpoint to outputs/emotion-classifier-minilm-0/checkpoint-117
loading configuration file config.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 384,
  "initializer_range": 0.02,
  "intermediate_size": 1536,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}


***** Running Evaluation *****
  Num examples = 399
  Batch size = 16
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
Saving model checkpoint to outputs/emotion-classifier-minilm-0/checkpoint-234
loading configuration file config.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 384,
  "initializer_range": 0.02,
  "intermediate_size": 1536,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}


***** Running Evaluation *****
  Num examples = 399
  Batch size = 16
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
Saving model checkpoint to outputs/emotion-classifier-minilm-0/checkpoint-351
loading configuration file config.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 384,
  "initializer_range": 0.02,
  "intermediate_size": 1536,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [outputs/emotion-classifier-minilm-0/checkpoint-234] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 399
  Batch size = 16
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
Saving model checkpoint to outputs/emotion-classifier-minilm-0/checkpoint-468
loading configuration file config.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 384,
  "initializer_range": 0.02,
  "intermediate_size": 1536,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [outputs/emotion-classifier-minilm-0/checkpoint-351] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 399
  Batch size = 16
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
Saving model checkpoint to outputs/emotion-classifier-minilm-0/checkpoint-585
loading configuration file config.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 384,
  "initializer_range": 0.02,
  "intermediate_size": 1536,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [outputs/emotion-classifier-minilm-0/checkpoint-468] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 399
  Batch size = 16
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
Saving model checkpoint to outputs/emotion-classifier-minilm-0/checkpoint-702
loading configuration file config.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 384,
  "initializer_range": 0.02,
  "intermediate_size": 1536,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

Deleting older checkpoint [outputs/emotion-classifier-minilm-0/checkpoint-585] due to args.save_total_limit


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from outputs/emotion-classifier-minilm-0/checkpoint-117 (score: 0.7142857142857143).

***** Running Prediction *****
  Num examples = 400
  Batch size = 16

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

     present       0.71      1.00      0.83       285
     neutral       0.00      0.00      0.00       115

    accuracy                           0.71       400
   macro avg       0.36      0.50      0.42       400
weighted avg       0.51      0.71      0.59       400

Training model for emotion detection with model sentence-transformers/all-MiniLM-L6-v2 using discretization to 3 classes

loading file vocab.txt from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/vocab.txt
loading file tokenizer.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/tokenizer.json
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/special_tokens_map.json
loading file tokenizer_config.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/tokenizer_config.json
loading file chat_template.jinja from cache at None

Map:   0%|          | 0/2660 [00:00<?, ? examples/s]

Map:   0%|          | 0/2660 [00:00<?, ? examples/s]

loading file vocab.txt from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/vocab.txt
loading file tokenizer.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/tokenizer.json
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/special_tokens_map.json
loading file tokenizer_config.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/tokenizer_config.json
loading file chat_template.jinja from cache at None
loading configuration file config.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 384,
  "initializer_range": 0.02,
  "intermediate_size": 1536,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading configuration file config.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 384,
  "initializer_range": 0.02,
  "intermediate_size": 1536,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weights file model.safetensors from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/model.safetensors

Stringifying the column:   0%|          | 0/2660 [00:00<?, ? examples/s]

Casting to class labels:   0%|          | 0/2660 [00:00<?, ? examples/s]

loading configuration file config.json from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 384,
  "id2label": {
    "0": "high",
    "1": "neutral",
    "2": "medium"
  },
  "initializer_range": 0.02,
  "intermediate_size": 1536,
  "label2id": {
    "high": 0,
    "medium": 2,
    "neutral": 1
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weights file model.safetensors from cache at /home/paulius/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/model.safetensors
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at sentence-transformers/all-MiniLM-L6-v2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
PyTorch: setting up devices
The model is already on multiple devices. Skipping the move to device specified in `args`.
***** Running training *****
  Num examples = 1,861
  Num Epochs = 20
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 2,340
  Number of trainable parameters = 339,075
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"