In [1]:
import os
from pathlib import Path
import numpy as np
import pandas as pd
import wandb
import unsloth
from datasets import Dataset
from transformers import AutoTokenizer
from finetune_mbert import train_eval_model
from experiment import preprocess_text

os.environ["CUDA_VISIBLE_DEVICES"]="0"

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
Unsloth: Your Flash Attention 2 installation seems to be broken. Using Xformers instead. No performance changes will be seen.
🦥 Unsloth Zoo will now patch everything to make training faster!

In [2]:
def preprocess(example):
    return {'text': preprocess_text(example['text']), 'labels': example['labels']}

def load_emotionality_dataset(tokenizer, label_bounds = {0: 'present'}, **tokenizer_args):
    DATA_PATH = Path("../data/2026-05-21/corpus_emotions.json")
    data = pd.read_json(DATA_PATH)
    labels = pd.cut(
        data['emotionality'], 
        bins=list(label_bounds.keys()) + [np.max(data['emotionality'])+1],
        labels=list(label_bounds.values()),
        right=False
    ).astype('object')
    data = Dataset.from_dict({'text': data['content'], 'labels': labels})
    data = data.map(preprocess)
    labels_map = {label: ind for ind, label in enumerate(set(data['labels']))}

    def tokenize(example):
        labels = list(map(lambda m: labels_map.get(m), example['labels']))
        example = tokenizer(example["text"], padding="max_length", truncation=True, **tokenizer_args)
        example['labels'] = labels
        return example

    final_dst = data.map(tokenize, batched=True, remove_columns=['text'])
    final_dst.set_format(type="torch")
    return final_dst, labels_map

## ModernBert

In [3]:
tokenizer_args = {
  "return_token_type_ids": "false",
  "max_length": 512
}
models_config = [
    ("VSSA-SDSA/LT-MLKM-modernBERT", "outputs/emotion-classifier-modernbert-unsloth")
]
label_config = [
    {0: 'neutral', 0.5: 'present'}, 
    {0: 'neutral', 0.5: 'medium', 1.5: 'high'},
    {0: 'neutral', 0.5: 'moderate', 1.0: 'high', 1.5: 'strong', 2.0: 'extreme'}
]

In [4]:
for model_name, output_dir in models_config:
    for ind, label_bounds in enumerate(label_config):
        print(f"Training model for emotion detection with model {model_name} using discretization to {len(label_bounds)} classes")
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        ds, labels_map = load_emotionality_dataset(tokenizer, label_bounds=label_bounds, **tokenizer_args)
        run = wandb.init(project="emotion-detection-lt-unsloth-8bit-lora", name=f"{model_name}-{len(label_bounds)}class-{ind}")
        train_eval_model(
            model_name=model_name,
            dataset=ds,
            labels_map=labels_map,
            use_lora=False,
            output_dir=f"{output_dir}-{ind}", 
            batch_size=2, 
            num_epochs=20, 
            eval_batch_size=16,
            report_to=['tensorboard', 'wandb']
        )

Training model for emotion detection with model VSSA-SDSA/LT-MLKM-modernBERT using discretization to 2 classes

Map:   0%|          | 0/2660 [00:00<?, ? examples/s]

Map:   0%|          | 0/2660 [00:00<?, ? examples/s]

wandb: ERROR Failed to detect the name of this notebook. You can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/paudan/.netrc.
wandb: Currently logged in as: danpaulius (danpaulius-ktu) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

wandb: Detected [huggingface_hub.inference] in use.
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai

Stringifying the column:   0%|          | 0/2660 [00:00<?, ? examples/s]

Casting to class labels:   0%|          | 0/2660 [00:00<?, ? examples/s]

==((====))==  Unsloth 2026.5.8: Fast Modernbert patching. Transformers: 5.5.0.
   \\   /|    NVIDIA H100 NVL. Num GPUs = 2. Max memory: 93.111 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 9.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Using bfloat16 full finetuning which cuts memory usage by 50%.
To enable float32 training, use `float32_mixed_precision = True` during FastLanguageModel.from_pretrained

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

ModernBertForSequenceClassification LOAD REPORT from: VSSA-SDSA/LT-MLKM-modernBERT
Key               | Status     |
------------------+------------+-
decoder.weight    | UNEXPECTED |
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Unsloth: Full finetuning is enabled, so .get_peft_model has no effect

The following columns in the Training set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.
skipped Embedding(64000, 768, padding_idx=50283): 46.875M params
skipped: 46.875M params
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,861 | Num Epochs = 20 | Total steps = 9,320
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 1 x 1) = 4
 "-____-"     Trainable parameters = 160,075,778 of 160,075,778 (100.00% trained)

The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-466
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-466/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-466/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-932
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-932/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-932/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-1398
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-1398/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-1398/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-1864
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-1864/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-1864/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-2330
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-2330/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-2330/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-2796
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-2796/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-2796/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-3262
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-3262/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-3262/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-3728
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-3728/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-3728/model.safetensors


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from outputs/emotion-classifier-modernbert-unsloth-0/checkpoint-1398 (score: 0.7443609022556391).
The following columns in the test set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Prediction *****
  Num examples = 400
  Batch size = 32

              precision    recall  f1-score   support

     present       0.79      0.89      0.84       285
     neutral       0.61      0.40      0.48       115

    accuracy                           0.75       400
   macro avg       0.70      0.65      0.66       400
weighted avg       0.73      0.75      0.74       400

Training model for emotion detection with model VSSA-SDSA/LT-MLKM-modernBERT using discretization to 3 classes

loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--VSSA-SDSA--LT-MLKM-modernBERT/snapshots/f69fbef425a0906fce7fa5dc40730f46473cc4c2/config.json
Model config ModernBertConfig {
  "architectures": [
    "ModernBertForMaskedLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 50281,
  "classifier_activation": "gelu",
  "classifier_bias": false,
  "classifier_dropout": 0.0,
  "classifier_pooling": "cls",
  "cls_token_id": 50281,
  "decoder_bias": true,
  "deterministic_flash_attn": false,
  "dtype": "bfloat16",
  "embedding_dropout": 0.0,
  "eos_token_id": 50282,
  "global_attn_every_n_layers": 3,
  "hidden_activation": "gelu",
  "hidden_size": 768,
  "initializer_cutoff_factor": 2.0,
  "initializer_range": 0.02,
  "intermediate_size": 1152,
  "layer_types": [
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention"
  ],
  "local_attention": 128,
  "max_position_embeddings": 8192,
  "mlp_bias": false,
  "mlp_dropout": 0.0,
  "model_type": "modernbert",
  "norm_bias": false,
  "norm_eps": 1e-05,
  "num_attention_heads": 12,
  "num_hidden_layers": 22,
  "pad_token_id": 50283,
  "repad_logits_with_grad": false,
  "rope_parameters": {
    "full_attention": {
      "rope_theta": 160000.0,
      "rope_type": "default"
    },
    "sliding_attention": {
      "rope_theta": 10000.0,
      "rope_type": "default"
    }
  },
  "sep_token_id": 50282,
  "sparse_pred_ignore_index": -100,
  "sparse_prediction": false,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "vocab_size": 64000
}

Map:   0%|          | 0/2660 [00:00<?, ? examples/s]

Map:   0%|          | 0/2660 [00:00<?, ? examples/s]

Stringifying the column:   0%|          | 0/2660 [00:00<?, ? examples/s]

Casting to class labels:   0%|          | 0/2660 [00:00<?, ? examples/s]

loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--VSSA-SDSA--LT-MLKM-modernBERT/snapshots/f69fbef425a0906fce7fa5dc40730f46473cc4c2/config.json
Model config ModernBertConfig {
  "architectures": [
    "ModernBertForMaskedLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 50281,
  "classifier_activation": "gelu",
  "classifier_bias": false,
  "classifier_dropout": 0.0,
  "classifier_pooling": "cls",
  "cls_token_id": 50281,
  "decoder_bias": true,
  "deterministic_flash_attn": false,
  "dtype": "bfloat16",
  "embedding_dropout": 0.0,
  "eos_token_id": 50282,
  "global_attn_every_n_layers": 3,
  "hidden_activation": "gelu",
  "hidden_size": 768,
  "initializer_cutoff_factor": 2.0,
  "initializer_range": 0.02,
  "intermediate_size": 1152,
  "layer_types": [
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention"
  ],
  "local_attention": 128,
  "max_position_embeddings": 8192,
  "mlp_bias": false,
  "mlp_dropout": 0.0,
  "model_type": "modernbert",
  "norm_bias": false,
  "norm_eps": 1e-05,
  "num_attention_heads": 12,
  "num_hidden_layers": 22,
  "pad_token_id": 50283,
  "repad_logits_with_grad": false,
  "rope_parameters": {
    "full_attention": {
      "rope_theta": 160000.0,
      "rope_type": "default"
    },
    "sliding_attention": {
      "rope_theta": 10000.0,
      "rope_type": "default"
    }
  },
  "sep_token_id": 50282,
  "sparse_pred_ignore_index": -100,
  "sparse_prediction": false,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "vocab_size": 64000
}

==((====))==  Unsloth 2026.5.8: Fast Modernbert patching. Transformers: 5.5.0.
   \\   /|    NVIDIA H100 NVL. Num GPUs = 2. Max memory: 93.111 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 9.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Using bfloat16 full finetuning which cuts memory usage by 50%.
To enable float32 training, use `float32_mixed_precision = True` during FastLanguageModel.from_pretrained

loading weights file model.safetensors from cache at /home/paudan/.cache/huggingface/hub/models--VSSA-SDSA--LT-MLKM-modernBERT/snapshots/f69fbef425a0906fce7fa5dc40730f46473cc4c2/model.safetensors

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

ModernBertForSequenceClassification LOAD REPORT from: VSSA-SDSA/LT-MLKM-modernBERT
Key               | Status     |
------------------+------------+-
decoder.weight    | UNEXPECTED |
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--VSSA-SDSA--LT-MLKM-modernBERT/snapshots/f69fbef425a0906fce7fa5dc40730f46473cc4c2/config.json
Model config ModernBertConfig {
  "architectures": [
    "ModernBertForMaskedLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 50281,
  "classifier_activation": "gelu",
  "classifier_bias": false,
  "classifier_dropout": 0.0,
  "classifier_pooling": "cls",
  "cls_token_id": 50281,
  "decoder_bias": true,
  "deterministic_flash_attn": false,
  "dtype": "bfloat16",
  "embedding_dropout": 0.0,
  "eos_token_id": 50282,
  "global_attn_every_n_layers": 3,
  "hidden_activation": "gelu",
  "hidden_size": 768,
  "initializer_cutoff_factor": 2.0,
  "initializer_range": 0.02,
  "intermediate_size": 1152,
  "layer_types": [
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention"
  ],
  "local_attention": 128,
  "max_position_embeddings": 8192,
  "mlp_bias": false,
  "mlp_dropout": 0.0,
  "model_type": "modernbert",
  "norm_bias": false,
  "norm_eps": 1e-05,
  "num_attention_heads": 12,
  "num_hidden_layers": 22,
  "pad_token_id": 50283,
  "repad_logits_with_grad": false,
  "rope_parameters": {
    "full_attention": {
      "rope_theta": 160000.0,
      "rope_type": "default"
    },
    "sliding_attention": {
      "rope_theta": 10000.0,
      "rope_type": "default"
    }
  },
  "sep_token_id": 50282,
  "sparse_pred_ignore_index": -100,
  "sparse_prediction": false,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "vocab_size": 64000
}

PyTorch: setting up devices

Unsloth: Full finetuning is enabled, so .get_peft_model has no effect

The following columns in the Training set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.
skipped Embedding(64000, 768, padding_idx=50283): 46.875M params
skipped: 46.875M params
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,861 | Num Epochs = 20 | Total steps = 9,320
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 1 x 1) = 4
 "-____-"     Trainable parameters = 160,076,547 of 160,076,547 (100.00% trained)

The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-466
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-466/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-466/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-932
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-932/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-932/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-1398
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-1398/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-1398/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-1864
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-1864/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-1864/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-2330
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-2330/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-2330/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-2796
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-2796/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-2796/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-3262
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-3262/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-3262/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-3728
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-3728/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-3728/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-4194
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-4194/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-4194/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-4660
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-4660/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-4660/model.safetensors


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from outputs/emotion-classifier-modernbert-unsloth-1/checkpoint-2330 (score: 0.6491228070175439).
The following columns in the test set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Prediction *****
  Num examples = 400
  Batch size = 32

              precision    recall  f1-score   support

      medium       0.67      0.86      0.75       251
        high       0.38      0.09      0.14        34
     neutral       0.52      0.31      0.39       115

    accuracy                           0.64       400
   macro avg       0.52      0.42      0.43       400
weighted avg       0.60      0.64      0.60       400

Training model for emotion detection with model VSSA-SDSA/LT-MLKM-modernBERT using discretization to 5 classes

loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--VSSA-SDSA--LT-MLKM-modernBERT/snapshots/f69fbef425a0906fce7fa5dc40730f46473cc4c2/config.json
Model config ModernBertConfig {
  "architectures": [
    "ModernBertForMaskedLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 50281,
  "classifier_activation": "gelu",
  "classifier_bias": false,
  "classifier_dropout": 0.0,
  "classifier_pooling": "cls",
  "cls_token_id": 50281,
  "decoder_bias": true,
  "deterministic_flash_attn": false,
  "dtype": "bfloat16",
  "embedding_dropout": 0.0,
  "eos_token_id": 50282,
  "global_attn_every_n_layers": 3,
  "hidden_activation": "gelu",
  "hidden_size": 768,
  "initializer_cutoff_factor": 2.0,
  "initializer_range": 0.02,
  "intermediate_size": 1152,
  "layer_types": [
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention"
  ],
  "local_attention": 128,
  "max_position_embeddings": 8192,
  "mlp_bias": false,
  "mlp_dropout": 0.0,
  "model_type": "modernbert",
  "norm_bias": false,
  "norm_eps": 1e-05,
  "num_attention_heads": 12,
  "num_hidden_layers": 22,
  "pad_token_id": 50283,
  "repad_logits_with_grad": false,
  "rope_parameters": {
    "full_attention": {
      "rope_theta": 160000.0,
      "rope_type": "default"
    },
    "sliding_attention": {
      "rope_theta": 10000.0,
      "rope_type": "default"
    }
  },
  "sep_token_id": 50282,
  "sparse_pred_ignore_index": -100,
  "sparse_prediction": false,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "vocab_size": 64000
}

Map:   0%|          | 0/2660 [00:00<?, ? examples/s]

Map:   0%|          | 0/2660 [00:00<?, ? examples/s]

Stringifying the column:   0%|          | 0/2660 [00:00<?, ? examples/s]

Casting to class labels:   0%|          | 0/2660 [00:00<?, ? examples/s]

loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--VSSA-SDSA--LT-MLKM-modernBERT/snapshots/f69fbef425a0906fce7fa5dc40730f46473cc4c2/config.json
Model config ModernBertConfig {
  "architectures": [
    "ModernBertForMaskedLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 50281,
  "classifier_activation": "gelu",
  "classifier_bias": false,
  "classifier_dropout": 0.0,
  "classifier_pooling": "cls",
  "cls_token_id": 50281,
  "decoder_bias": true,
  "deterministic_flash_attn": false,
  "dtype": "bfloat16",
  "embedding_dropout": 0.0,
  "eos_token_id": 50282,
  "global_attn_every_n_layers": 3,
  "hidden_activation": "gelu",
  "hidden_size": 768,
  "initializer_cutoff_factor": 2.0,
  "initializer_range": 0.02,
  "intermediate_size": 1152,
  "layer_types": [
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention"
  ],
  "local_attention": 128,
  "max_position_embeddings": 8192,
  "mlp_bias": false,
  "mlp_dropout": 0.0,
  "model_type": "modernbert",
  "norm_bias": false,
  "norm_eps": 1e-05,
  "num_attention_heads": 12,
  "num_hidden_layers": 22,
  "pad_token_id": 50283,
  "repad_logits_with_grad": false,
  "rope_parameters": {
    "full_attention": {
      "rope_theta": 160000.0,
      "rope_type": "default"
    },
    "sliding_attention": {
      "rope_theta": 10000.0,
      "rope_type": "default"
    }
  },
  "sep_token_id": 50282,
  "sparse_pred_ignore_index": -100,
  "sparse_prediction": false,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "vocab_size": 64000
}

==((====))==  Unsloth 2026.5.8: Fast Modernbert patching. Transformers: 5.5.0.
   \\   /|    NVIDIA H100 NVL. Num GPUs = 2. Max memory: 93.111 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 9.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Using bfloat16 full finetuning which cuts memory usage by 50%.
To enable float32 training, use `float32_mixed_precision = True` during FastLanguageModel.from_pretrained

loading weights file model.safetensors from cache at /home/paudan/.cache/huggingface/hub/models--VSSA-SDSA--LT-MLKM-modernBERT/snapshots/f69fbef425a0906fce7fa5dc40730f46473cc4c2/model.safetensors

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

ModernBertForSequenceClassification LOAD REPORT from: VSSA-SDSA/LT-MLKM-modernBERT
Key               | Status     |
------------------+------------+-
decoder.weight    | UNEXPECTED |
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
loading configuration file config.json from cache at /home/paudan/.cache/huggingface/hub/models--VSSA-SDSA--LT-MLKM-modernBERT/snapshots/f69fbef425a0906fce7fa5dc40730f46473cc4c2/config.json
Model config ModernBertConfig {
  "architectures": [
    "ModernBertForMaskedLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 50281,
  "classifier_activation": "gelu",
  "classifier_bias": false,
  "classifier_dropout": 0.0,
  "classifier_pooling": "cls",
  "cls_token_id": 50281,
  "decoder_bias": true,
  "deterministic_flash_attn": false,
  "dtype": "bfloat16",
  "embedding_dropout": 0.0,
  "eos_token_id": 50282,
  "global_attn_every_n_layers": 3,
  "hidden_activation": "gelu",
  "hidden_size": 768,
  "initializer_cutoff_factor": 2.0,
  "initializer_range": 0.02,
  "intermediate_size": 1152,
  "layer_types": [
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention"
  ],
  "local_attention": 128,
  "max_position_embeddings": 8192,
  "mlp_bias": false,
  "mlp_dropout": 0.0,
  "model_type": "modernbert",
  "norm_bias": false,
  "norm_eps": 1e-05,
  "num_attention_heads": 12,
  "num_hidden_layers": 22,
  "pad_token_id": 50283,
  "repad_logits_with_grad": false,
  "rope_parameters": {
    "full_attention": {
      "rope_theta": 160000.0,
      "rope_type": "default"
    },
    "sliding_attention": {
      "rope_theta": 10000.0,
      "rope_type": "default"
    }
  },
  "sep_token_id": 50282,
  "sparse_pred_ignore_index": -100,
  "sparse_prediction": false,
  "tie_word_embeddings": true,
  "transformers_version": "5.5.0",
  "vocab_size": 64000
}

PyTorch: setting up devices

Unsloth: Full finetuning is enabled, so .get_peft_model has no effect

The following columns in the Training set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.
skipped Embedding(64000, 768, padding_idx=50283): 46.875M params
skipped: 46.875M params
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,861 | Num Epochs = 20 | Total steps = 9,320
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 1 x 1) = 4
 "-____-"     Trainable parameters = 160,078,085 of 160,078,085 (100.00% trained)

The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-466
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-466/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-466/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-932
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-932/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-932/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-1398
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-1398/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-1398/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-1864
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-1864/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-1864/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-2330
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-2330/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-2330/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-2796
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-2796/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-2796/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-3262
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-3262/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-3262/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-3728
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-3728/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-3728/model.safetensors
The following columns in the Evaluation set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 399
  Batch size = 32
[tensorboardX.x2num|WARNING]NaN or Inf found in input tensor.
Saving model checkpoint to outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-4194
Configuration saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-4194/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-4194/model.safetensors


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from outputs/emotion-classifier-modernbert-unsloth-2/checkpoint-1864 (score: 0.41102756892230574).
The following columns in the test set don't have a corresponding argument in `ModernBertForSequenceClassification.forward` and have been ignored: token_type_ids. If token_type_ids are not expected by `ModernBertForSequenceClassification.forward`,  you can safely ignore this message.

***** Running Prediction *****
  Num examples = 400
  Batch size = 32

              precision    recall  f1-score   support

    moderate       0.36      0.39      0.37       119
      strong       0.20      0.23      0.21        13
     extreme       0.20      0.10      0.13        21
        high       0.45      0.42      0.44       132
     neutral       0.50      0.53      0.51       115

    accuracy                           0.42       400
   macro avg       0.34      0.33      0.33       400
weighted avg       0.42      0.42      0.42       400